kind: pipeline
type: docker
name: default
clone:
  disable: true

steps:
  - name: clone-test
    image: alpine/git
    pull: if-not-exists # 如果在本地缓存中找不到image，则仅拉取image..
    commands:
      - git config --global http.version HTTP/1.1
      - git clone https://github.com/one-thing-one-world/blog-client.git
      - git version

  - name: install && build
    image: node:16
    pull: always
    commands:
      - pwd
      - cd blog-client
      - node -v
      # - yarn
      # - yarn / hozhe \--------
      # - yarn add react-scripts
      # - yarn build:prod
      - ls
      - pwd

  - name: sshs
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: docker_host
      username:
        from_secret: docker_username
      port: 22
      password:
        from_secret: docker_password
      script:
        - ls
        - pwd
        - cd /usr/share/nginx/blog.cn/blog-client
        # - rm -rf  build
        - echo 'delete build successs ===>'
        - echo
        - ssh -o
        - ls
        - pwd

  - name: upload
    image: appleboy/drone-scp
    pull: always
    settings:
      debug: true
      source:
        - /drone/src/blog-client
      host:
        from_secret: docker_host
      username:
        from_secret: docker_username
      port: 22
      password:
        from_secret: docker_password
        # target:
        #   /usr/share/nginx/blog.cn/
        # target: /root/front_workspace
      target: /usr/share

      when:
        branch:
          include:
            - master
        event:
          - push
          - merge
      script:
        # - nginx -s reload
        # - cd /usr/share/nginx/blog.cn/
        - echo "hello deploy"
        # - docker build -t deploy-front deploy
        # - docker-compose up deploy-front
        # - docker ps -a

        - ls
        - pwd
        - echo upload success ===>

trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
