kind: pipeline
type: docker
name: front
clone:
  disable: true

steps:
  - name: clone-code
    image: alpine/git:2.36.3
    # pull: if-not-exists # 如果在本地缓存中找不到image，则仅拉取image
    pull: always

    commands:
      - git version
      - git config --global http.version HTTP/1.1
      - git clone https://github.com/one-thing-one-world/blog-client.git

  - name: install && build
    image: node:16
    pull: always
    commands:
      - node -v
      # - yarn

  - name: upload
    image: appleboy/drone-scp
    pull: always
    settings:
      debug: true
      source:
        - blog-client/
      host:
        from_secret: docker_host
      username:
        from_secret: docker_username
      port: 22
      password:
        from_secret: docker_password
      target: /root/front_workspace

      when:
        branch:
          include:
            - master
        event:
          - push
          - merge
      script:
        - echo upload <=== success ===>

  - name: sshs
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: docker_host
      username:
        from_secret: docker_username
      port: 22
      password:
        from_secret: docker_password
      script:
        - cd front_workspace/blog-client/
        - docker stop deploy
        - docker rf -f  deploy
        - docker rmi deployfront
        - docker ps -a
        - docker build -t deployfront .
        - docker run --name deploy -i -p 80:80 deployfront
        - echo drone-ssh <=== success ===>
trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
